[nl]
languageName = "Nederlands"
contentDir = "content/nl"
weight = 1
[nl.params.opengraph]
locale = "nl_NL"
[nl.params.head]
tagline = "Bijbelwetenschappen en toegankelijkheid"
[nl.params.footer]
license = "Gelicenseerd onder <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (CC BY-NC-SA 4.0)</a> | <a href='https://www.netlify.com'>Uitgerold en gehost door Netlify</a>"
[en]
languageName = "English"
contentDir = "content/en"
weight = 2
[en.params.head]
tagline = "Biblical Science Accessibility"
[en.params.footer]
license = "Licensed under <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (CC BY-NC-SA 4.0)</a> | <a href='https://www.netlify.com'>Uitgerold en gehost door Netlify</a>"