[nl]
languageName = "Nederlands"
contentDir = "content/nl"
weight = 1
[nl.params.opengraph]
locale = "nl_NL"
[nl.params.head]
tagline = "Bijbelwetenschappen en toegankelijkheid"
[en]
languageName = "English"
contentDir = "content/en"
weight = 2
[en.params.head]
tagline = "Biblical Science Accessibility"
