[nl]
  contentDir = "content"
  languageName = "Nederlands"
  languageCode = "nl-nl"
  weight = 1
  [nl.params.opengraph]
  locale = "nl_NL"
[en]
  contentDir = "content/en"
  languageName = "English"
  languageCode = "en-us"
  weight = 2
