[main]
    separator = "-"
    description = "Biblical Science Accessibility"
    enableLanguageSelectionStorage = false
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.colorMode]
        enabled = false
        modes = ["light", "dark"]
        toggle = true
    [main.internalLinks]
        validate = true
        pretty = true
    [main.externalLinks]
        cue = true
        tab = true
    [main.build]
        transpiler = "libsass"

[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false

[navigation]
    anchor = true
    color = "body"
    fixed = true
    offset = "5.5rem"
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
    [navigation.search]
        enabled = false
        modal = true

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem"
    purge = false

[schema]
    type = "Organization"
    name = "Project Didymus"
    locale = "en-US"
    github = "https://github.com/ProjectDidymus"

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[modules.bookshop]
  integration = "optional"
