site_url: https://didymus.info
display_url: https://beta.didymus.info
local_backend: true
backend:
  name: git-gateway
  branch: beta
  squash_merges: true
locale: "nl"
publish_mode: editorial_workflow
i18n:
  structure: multiple_folders
  locales: [nl, en]
  default_locale: nl
media_folder: static/img
public_folder: /img
collections:
  - name: content
    label: Inhoud
    extension: md
    format: yaml-frontmatter
    folder: content
    i18n: true
    nested:
      depth: 2
      subfolders: false
      meta:
        path:
          widget: string
          label: "Pad"
          index_file: "_index"
    fields:
      - label: Titel
        name: title
        widget: string
        i18n: true
      - label: Omschrijving
        name: description
        widget: text
        i18n: true
      - label: Datum
        name: date
        widget: "datetime"
        default: "{{now}}"
        date_format: "YYYY-MM_DD"
      - label: Concept
        name: draft"
        widget: boolean
        default: true
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: Inhoud
        name: body
        widget: markdown
        i18n: true
      - label: Gewicht
        name: weight
        widget: "number"
        value_type: "int"
        min: 1
        max: 100
      - label: "Niet opnemen in zoekresultaten"
        name: searchExclude
        widget: boolean
        default: false
